# Naive Bayes Classifier with Scikit

In [1]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

dataset = datasets.load_iris()

model = GaussianNB()
model.fit(dataset.data, dataset.target)
print(model)

expected = dataset.target
predicted = model.predict(dataset.data)

print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB()
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [2]:
import numpy as np

def prepare_person_dataset(fname):
    genders = ['male', 'female']
    persons = []

    with open(fname) as fh:
        for line in fh:
            persons.append(line.strip().split())

    firstnames = []
    dataset = []

    for person in persons:
        firstnames.append((person[0], person[4]))
        height_weight = (float(person[2]), float(person[3]))
        dataset.append((height_weight, person[4]))
    return dataset

learnset = prepare_person_dataset('person_data.txt')
testset = prepare_person_dataset('person_data_testset.txt')

print(learnset)

[((184.0, 73.0), 'male'), ((149.0, 52.0), 'female'), ((174.0, 63.0), 'female'), ((175.0, 67.0), 'male'), ((183.0, 81.0), 'female'), ((187.0, 60.0), 'male'), ((192.0, 96.0), 'male'), ((204.0, 91.0), 'male'), ((180.0, 66.0), 'male'), ((184.0, 52.0), 'male'), ((174.0, 53.0), 'male'), ((177.0, 91.0), 'male'), ((138.0, 37.0), 'female'), ((200.0, 82.0), 'male'), ((193.0, 79.0), 'male'), ((189.0, 79.0), 'male'), ((145.0, 59.0), 'female'), ((188.0, 53.0), 'male'), ((187.0, 81.0), 'male'), ((187.0, 99.0), 'male'), ((190.0, 81.0), 'male'), ((161.0, 48.0), 'female'), ((179.0, 75.0), 'female'), ((180.0, 67.0), 'male'), ((155.0, 48.0), 'male'), ((201.0, 122.0), 'male'), ((162.0, 62.0), 'female'), ((148.0, 49.0), 'female'), ((171.0, 50.0), 'male'), ((196.0, 86.0), 'female'), ((163.0, 46.0), 'female'), ((159.0, 37.0), 'female'), ((163.0, 53.0), 'male'), ((150.0, 39.0), 'female'), ((170.0, 56.0), 'female'), ((191.0, 55.0), 'male'), ((175.0, 37.0), 'male'), ((169.0, 78.0), 'female'), ((167.0, 59.0), 'f

In [4]:
model = GaussianNB()

w, l = zip(*learnset)
w = np.array(w)
l = np.array(l)

model.fit(w, l)
print(model)

w, l = zip(*testset)
w = np.array(w)
l = np.array(l)

predicted = model.predict(w)

print(predicted)
print(l)

print(metrics.classification_report(l, predicted))
print(metrics.confusion_matrix(l, predicted))


GaussianNB()
['female' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'female' 'female' 'female' 'female' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'female' 'male' 'female' 'female' 'male' 'male'
 'female' 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'female' 'male' 'male' 'female' 'female'
 'male' 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'female'
 'male' 'female' 'female' 'male' 'female' 'female' 'male' 'female'
 'female' 'male' 'female' 'female' 'female' 'female' 'male' 'female'
 'female' 'female' 'female' 'female' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'female' 'female' 'male' 'male' 'female' 'male'
 'female' 'female' 'female' 'male' 'female' 'male']
['female' 'male' 'male' 'female' 'female' 'male' 'male' 'male' 'female'
 'female' 'female' 'female' 'female' 'female' 'male' 'male' 'male'
 'female' 'female