# Introduction to TensorFlow

This source code was written for TensorFlow v1 instead of v2. That is why this is not fully completed.

In [5]:
import tensorflow as tf

c1 = tf.constant(0.034)
c2 = tf.constant(1000.0)

x = tf.multiply(c1, c1)
y = tf.multiply(c1, c2)

final_node = tf.add(x, y)

final_node


<tf.Tensor: shape=(), dtype=float32, numpy=34.001156>

In [6]:
c1 = tf.constant(0.034, dtype=tf.float64)
c2 = tf.constant(1000.0, dtype=tf.float64)

x = tf.multiply(c1, c1)
y = tf.multiply(c1, c2)

final_node = tf.add(x, y)

final_node

<tf.Tensor: shape=(), dtype=float64, numpy=34.001156>

In [7]:
c1 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)
c2 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)

x = tf.multiply(c1, c1)
y = tf.multiply(c1, c2)

final_node = tf.add(x, y)

final_node

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 23.12, 165.62,   2.88, 162.  ])>

In [8]:
c1 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)
c2 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)

x = tf.multiply(c1, c1)
y = tf.multiply(c1, c2)

final_node = tf.add(x, y)

print(c1)
print(x)
print(final_node)

tf.Tensor([ 3.4  9.1 -1.2  9. ], shape=(4,), dtype=float64)
tf.Tensor([11.56 82.81  1.44 81.  ], shape=(4,), dtype=float64)
tf.Tensor([ 23.12 165.62   2.88 162.  ], shape=(4,), dtype=float64)


In [11]:
x = tf.range(12)
x2 = tf.reshape(tensor=x, shape=(3, 4))
x2 = tf.reduce_sum(x2)

x3 = tf.eye(5, 5)

x3

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [12]:
p = tf.constant(0.034)
c = tf.constant(1000.0)

x = tf.add(c, tf.multiply(p, c))
x = tf.add(x, tf.multiply(p, x))

x

<tf.Tensor: shape=(), dtype=float32, numpy=1069.156>

In [13]:
# W = tf.Variable([.5], dtype=tf.float32)
# b = tf.Variable([-1], dtype=tf.float32)
# x = tf.placeholder(tf.float32)

# model = W * x + b

# model


AttributeError: module 'tensorflow' has no attribute 'placeholder'